menu:
  keppler_languages:
    name: Keppler Languages
    current: ['/admin/locales/languages']
    url_path: /admin/locales/languages
    icon: globe
    model: KepplerLanguages::Language
    enviroment: development
