# Connect on a TCP socket. Omitted by default since the client uses a
# domain socket that doesn't need configuration. Windows does not have
# domain sockets, so uncomment these lines.
#host: localohst
#port: 5432

default: &default
  host: <%= Rails.application.secrets.database['host'] %>
  adapter: mysql2
  encoding: utf8
  database: <%= Rails.application.secrets.database['name'] %>
  pool: 5
  username: <%= Rails.application.secrets.database['username'] %>
  password: <%= Rails.application.secrets.database['password'] %>
  template: template0

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default